/* Copyright 1995-2001 Roger P. Woods, M.D. */
/* Modified: 5/16/01 */

/*
 * Reads a particular plane of a file from disk to the
 *  specified address.
 *
 * NOTE: This routine assumes that memory has been allocated
 *  such that the memory locations of the data are all
 *  contiguous as occurs when allocating using create_vol3().
 *
 * If this assumption is not true, the result will be a mess.
 *
 * Returns:
 *	0 if data read successfully
 *	error code if not read successfully
 */

#include "AIR.h"

AIR_Error AIR_quickread(AIR_Pixels *data, const char *infile, const unsigned int plane)

{
	struct AIR_Fptrs	fps;
	int 		dummy[8];
	float 		globalscale;
	struct AIR_Key_info plane_info;

	/*Initialize*/	
	globalscale=AIR_open_header(infile,&fps,&plane_info,dummy);
	if(fps.errcode!=0){
	
		AIR_Error errcode=fps.errcode;
		AIR_close_header(&fps);
		return errcode;
	}

	/*Read the image*/
	{
		float scale=AIR_consult_header(infile,&fps,&plane_info,plane,dummy);
		if(fps.errcode!=0){
			AIR_Error errcode=fps.errcode;
			AIR_close_header(&fps);
			return errcode;
		}
#if(AIR_CONFIG_DECOMPRESS!=0)
                if(fps.image_was_compressed){
                    printf("%s: %d: ",__FILE__,__LINE__);
                    printf("this program accesses data one plane at a time and does not support compressed images like %s\n",infile);
                    AIR_close_header(&fps);
                    return AIR_PLANEWISE_DECOMPRESS_READ_ERROR;
                }
#endif
		{
			AIR_Error errcode=AIR_read_image(data,&(fps.fp_img),&plane_info,dummy,scale*globalscale);
			if(errcode!=0){
				printf("%s: %d: ",__FILE__,__LINE__);
				printf("failed to read plane %i of %s\n",plane+1,infile);
				AIR_close_header(&fps);
				return errcode;
			}
		}
	}
#if 0	/* AIR_CONFIG_DECOMPRESS!=0 */ /* Support for reading compressed images--NOT RECOMMENDED */
        if(fps.image_was_compressed){
            /* close_header() will invoke pclose() */
            /* Consume the remainder of the input stream so no error is generated by pclose() */
            while(getc(fps.fp_img)!=EOF);
        }
#endif
	AIR_close_header(&fps);
	if(fps.errcode!=0){
		printf("%s: %d: ",__FILE__,__LINE__);
		printf("failed to close header or image file of %s\n",infile);
		return fps.errcode;
	}
	return 0;	
}

