# Copyright (C) 2016 The Regents of the University of California
# Authored by David W. Shattuck, Ph.D.
BaseDir = ../../
Name    := $(shell basename `pwd`)
LocalIncludes = -I../include
LocalIncludes = -I../../surflib
LocalLibs = -lsurflib16a1
LocalSrcFiles = ../dfs/marchingcubes.cpp
include $(BaseDir)makefile.template

